// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modulith.Modules.Users.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modulith.Modules.Users.Persistence.Migrations;

[DbContext(typeof(UsersDbContext))]
[Migration("20260427100351_AddConsentPolicyVersion")]
partial class AddConsentPolicyVersion
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("users")
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Modulith.Modules.Users.Domain.Consent", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("ConsentKey")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("consent_key");

                b.Property<bool>("Granted")
                    .HasColumnType("boolean")
                    .HasColumnName("granted");

                b.Property<string>("GrantedFromIp")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)")
                    .HasColumnName("granted_from_ip");

                b.Property<string>("GrantedUserAgent")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("granted_user_agent");

                b.Property<string>("PolicyVersion")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("policy_version");

                b.Property<DateTimeOffset>("RecordedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("recorded_at");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_consents");

                b.HasIndex("UserId", "ConsentKey")
                    .HasDatabaseName("ix_consents_user_id_consent_key");

                b.ToTable("consents", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.ExternalLogin", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("LinkedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("linked_at");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("provider");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("subject");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_external_logins");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_external_logins_user_id");

                b.HasIndex("Provider", "Subject")
                    .IsUnique()
                    .HasDatabaseName("ix_external_logins_provider_subject");

                b.ToTable("external_logins", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.PendingEmailChange", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("NewEmail")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)")
                    .HasColumnName("new_email");

                b.Property<Guid>("TokenId")
                    .HasColumnType("uuid")
                    .HasColumnName("token_id");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_pending_email_changes");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasDatabaseName("ix_pending_email_changes_user_id");

                b.ToTable("pending_email_changes", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.PendingExternalLogin", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset?>("ConsumedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("consumed_at");

                b.Property<string>("CreatedFromIp")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)")
                    .HasColumnName("created_from_ip");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("display_name");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)")
                    .HasColumnName("email");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<bool>("IsExistingUser")
                    .HasColumnType("boolean")
                    .HasColumnName("is_existing_user");

                b.Property<DateTimeOffset>("IssuedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("issued_at");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("provider");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("subject");

                b.Property<byte[]>("TokenHash")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("token_hash");

                b.Property<string>("UserAgent")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("user_agent");

                b.HasKey("Id")
                    .HasName("pk_pending_external_logins");

                b.HasIndex("ExpiresAt")
                    .HasDatabaseName("ix_pending_external_logins_expires_at");

                b.HasIndex("TokenHash")
                    .IsUnique()
                    .HasDatabaseName("ix_pending_external_logins_token_hash");

                b.HasIndex("Provider", "Subject")
                    .IsUnique()
                    .HasDatabaseName("ix_pending_external_logins_provider_subject")
                    .HasFilter("consumed_at IS NULL");

                b.ToTable("pending_external_logins", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("CreatedFromIp")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)")
                    .HasColumnName("created_from_ip");

                b.Property<string>("DeviceFingerprint")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("device_fingerprint");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<DateTimeOffset>("IssuedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("issued_at");

                b.Property<DateTimeOffset?>("RevokedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("revoked_at");

                b.Property<Guid?>("RotatedTo")
                    .HasColumnType("uuid")
                    .HasColumnName("rotated_to");

                b.Property<byte[]>("TokenHash")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("token_hash");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_refresh_tokens");

                b.HasIndex("ExpiresAt")
                    .HasDatabaseName("ix_refresh_tokens_expires_at");

                b.HasIndex("TokenHash")
                    .IsUnique()
                    .HasDatabaseName("ix_refresh_tokens_token_hash");

                b.HasIndex("UserId", "RevokedAt")
                    .HasDatabaseName("ix_refresh_tokens_user_id_revoked_at");

                b.ToTable("refresh_tokens", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.SingleUseToken", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset?>("ConsumedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("consumed_at");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<DateTimeOffset>("IssuedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("issued_at");

                b.Property<int>("Purpose")
                    .HasColumnType("integer")
                    .HasColumnName("purpose");

                b.Property<byte[]>("TokenHash")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("token_hash");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_user_tokens");

                b.HasIndex("ExpiresAt")
                    .HasDatabaseName("ix_user_tokens_expires_at");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_user_tokens_user_id");

                b.HasIndex("TokenHash", "Purpose")
                    .IsUnique()
                    .HasDatabaseName("ix_user_tokens_token_hash_purpose");

                b.ToTable("user_tokens", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.TermsAcceptance", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("AcceptedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("accepted_at");

                b.Property<string>("AcceptedFromIp")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)")
                    .HasColumnName("accepted_from_ip");

                b.Property<string>("UserAgent")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("user_agent");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<string>("Version")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_terms_acceptances");

                b.HasIndex("UserId", "Version")
                    .IsUnique()
                    .HasDatabaseName("ix_terms_acceptances_user_id_version");

                b.ToTable("terms_acceptances", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("created_by");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("display_name");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)")
                    .HasColumnName("email");

                b.Property<bool>("HasCompletedOnboarding")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true)
                    .HasColumnName("has_completed_onboarding");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text")
                    .HasColumnName("password_hash");

                b.Property<string>("Role")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasDefaultValue("user")
                    .HasColumnName("role");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("updated_by");

                b.Property<uint>("xmin")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("Id")
                    .HasName("pk_users");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasDatabaseName("ix_users_email");

                b.ToTable("users", "users");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.ExternalLogin", b =>
            {
                b.HasOne("Modulith.Modules.Users.Domain.User", null)
                    .WithMany("ExternalLogins")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_external_logins_users_user_id");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.PendingEmailChange", b =>
            {
                b.HasOne("Modulith.Modules.Users.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_pending_email_changes_users_user_id");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.RefreshToken", b =>
            {
                b.HasOne("Modulith.Modules.Users.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_refresh_tokens_users_user_id");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.SingleUseToken", b =>
            {
                b.HasOne("Modulith.Modules.Users.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_user_tokens_users_user_id");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.TermsAcceptance", b =>
            {
                b.HasOne("Modulith.Modules.Users.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_terms_acceptances_users_user_id");
            });

        modelBuilder.Entity("Modulith.Modules.Users.Domain.User", b =>
            {
                b.Navigation("ExternalLogins");
            });
#pragma warning restore 612, 618
    }
}
