// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modulith.Modules.Notifications.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modulith.Modules.Notifications.Persistence.Migrations;

[DbContext(typeof(NotificationsDbContext))]
[Migration("20260427094905_AddNotificationLogDeliveryStatus")]
partial class AddNotificationLogDeliveryStatus
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("notifications")
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Modulith.Modules.Notifications.Domain.NotificationLog", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("DeliveryStatus")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("delivery_status");

                b.Property<Guid>("IdempotencyKey")
                    .HasColumnType("uuid")
                    .HasColumnName("idempotency_key");

                b.Property<int>("NotificationType")
                    .HasColumnType("integer")
                    .HasColumnName("notification_type");

                b.Property<string>("RecipientEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("character varying(320)")
                    .HasColumnName("recipient_email");

                b.Property<DateTimeOffset>("SentAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("sent_at");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("subject");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_notification_logs");

                b.HasIndex("IdempotencyKey")
                    .IsUnique()
                    .HasDatabaseName("ix_notification_logs_idempotency_key");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_notification_logs_user_id");

                b.ToTable("notification_logs", "notifications");
            });
#pragma warning restore 612, 618
    }
}
