// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modulith.Modules.Notifications.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modulith.Modules.Notifications.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260511192851_AddBellNotifications")]
    partial class AddBellNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulith.Modules.Notifications.Domain.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("delivery_status");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<DateTimeOffset?>("SendingClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sending_claimed_at");

                    b.Property<Guid?>("SendingLeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("sending_lease_token");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_logs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_logs_idempotency_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_logs_user_id");

                    b.ToTable("notification_logs", "notifications");
                });

            modelBuilder.Entity("Modulith.Modules.Notifications.Domain.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BellEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("bell_enabled");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_preferences");

                    b.HasIndex("UserId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_preferences_user_id_category");

                    b.ToTable("notification_preferences", "notifications");
                });

            modelBuilder.Entity("Modulith.Modules.Notifications.Domain.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LinkHref")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("link_href");

                    b.Property<string>("LinkLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("link_label");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<DateTimeOffset>("RetentionUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_until");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_user_notifications");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_notifications_expires_at");

                    b.HasIndex("RetentionUntil")
                        .HasDatabaseName("ix_user_notifications_retention_until");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .HasDatabaseName("ix_user_notifications_recipient_user_id_created_at");

                    b.HasIndex("RecipientUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_user_notifications_recipient_user_id_idempotency_key");

                    b.HasIndex("RecipientUserId", "ArchivedAt", "CreatedAt")
                        .HasDatabaseName("ix_user_notifications_recipient_user_id_archived_at_created_at");

                    b.HasIndex("RecipientUserId", "ReadAt", "CreatedAt")
                        .HasDatabaseName("ix_user_notifications_recipient_user_id_read_at_created_at");

                    b.ToTable("user_notifications", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
